### PR TITLE
Remove internal build support

### PR DESCRIPTION
**Pull request by ntadej**
Cherry-pick of #1000 into `opengl-2`.

### CODE REVIEW

**Comment by ntadej** [comment]
This is now more of a prototype cherry-pick to the `opengl-2` branch.

I want to ask @ovivoda and @louvers on how to handle this with the least overhead. The cleanest would be ine direct PR per original PR?

Note that I'll also enable Qt CI, the rest is up to individual platform maintainers.

**Comment by ovivoda** [comment]
@ntadej maybe we can experiment on another branch then merge into main one?

**Comment by ntadej** [comment]
Not sure I understand the comment. Everything that will get here should be merged into `main` first and then we selectively pick PRs that may be relevant. The question is just how do you prefer to do it?

**Comment by ovivoda** [comment]
@ntadej ah sorry, I think I understood the question wrong.

**Comment by ntadej** [comment]
Will still open PRs for CI to run, but will merge them directly then.

**Pull request merged**
