### PR TITLE
Upgrade libs and remove Jetifier

### PR DESCRIPTION
**Pull request by carlonzo**
Upgrade dependencies to remove `com.android.support` dependency and drop jetifier:
- upgrade Google location
- upgrade LeakCanary
- upgrade robolectric

### CODE REVIEW

**Comment by tir38** [comment]
Do you need to bump all of these at the same time? Are these all needed to remove Jetifier?

**Comment by carlonzo** [comment]
if I want to remove the Jetifier flag from the project, yes as all 3 libs depend on a `com.android.support.*` lib.

if the goal is just to remove `com.android.support` from the main library so users can drop jetifier, then no. Robolectric is just included in test config classpath and leakcanary for the demo app.

**Comment by ntadej** [comment]
Hi @carlonzo, any update on this pull request? It looks like it would be useful to get in.

**Comment by carlonzo** [comment]
> Hi @carlonzo, any update on this pull request? It looks like it would be useful to get in.

thanks @ntadej I actually forgot I didnt update this. let me update and make CI green

**Comment by birkskyum** [comment]
@carlonzo , was it possible to make green ci here, or is something blocking it?

**Comment by carlonzo** [comment]
I had issue building it locally and went for holidays. I've to go back to this unless someone wants to take over

**Comment by carlonzo** [comment]
@birkskyum I built it locally again and everything is fine.

I am running `./gradlew --parallel --max-workers=8 -Pmapbox.buildtype=debug -Pmapbox.stl=c++_static -Dorg.gradle.internal.http.socketTimeout=360000 -Dorg.gradle.internal.http.connectionTimeout=360000 -Pmapbox.abis=none :MapboxGLAndroidSDK:testDebugUnitTest --info` and is green. any tip?

**Comment by birkskyum** [comment]
It mentions that "Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0."

The current setup is for Gradle 3.6.3, but for some reason it's using gradle 7.

There is another PR here #456 , which is an attempt at upgrading gradle, but currently, that is requiring an update of [android-sdk-versions-plugin](https://github.com/mapbox/android-sdk-versions-plugin) to >= v1.1.1, which for some reason isn't published to [maven](https://search.maven.org/artifact/com.mapbox.mapboxsdk/mapbox-android-sdk-versions/1.1.0/jar).

**Comment by carlonzo** [comment]
Yeah actually i noticed that some time ago. I opened an issue here https://github.com/mapbox/android-sdk-versions-plugin/issues/43

Options i see :
1- we could fork and publish internally until the issue is solved?
2- could we get rid of the plugin or just disable until it is available?

**Comment by birkskyum** [comment]
I'm cool with either. What is the consequence of removing it in the repo?

**Comment by carlonzo** [comment]
so what the plugin does is registering a [task](https://github.com/mapbox/android-sdk-versions-plugin/blob/master/src/main/groovy/com/mapbox/android/sdk/versions/SaveSDKVersionInfoTask.groovy) that stores a file in `src/main/asset/com.mapbox.mapboxsdk` with versionCode and versionName.

I cannot find where it is read. if we remove the plugin it compiles fine but maybe somewhere it fails at runtime looking for this asset. I could suggest to copy-paste the task and just have this asset file generated. best would be if we can find where this file is read and how/why its used. lets play it lazy and create the task?

**Comment by carlonzo** [comment]
btw @birkskyum the `"Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0."` message is just a warning. this is not what is stopping the build. I found the issue. we can move the discussion about AGP upgrade and plugin removal to the PR https://github.com/maplibre/maplibre-gl-native/pull/456

**Comment by carlonzo** [comment]
@birkskyum I can reproduce the issue from CI on my local. this is probably due to robolectric upgrade. the robolectric upgrade was necessary to remove jetifier so I cannot revert that change.

solution here is to update CI to compile using JDK 11. I will do that on a separate PR then we can rebase this PR once/if the patch its merged

**Comment by carlonzo** [comment]
will rebase and try again once this is merged https://github.com/maplibre/maplibre-gl-native/pull/474

**Comment by birkskyum** [comment]
I closed/reopened in an attempt to trigger the CI

**Review by birkskyum — APPROVED** [review]
Thanks for this!

**Comment by carlonzo** [comment]
OMG finally! Thanks for the support

**Comment by ntadej** [comment]
Thank you for your efforts!

**Pull request merged**
