### PR TITLE
Enable C++ unit tests on macOS

### PR DESCRIPTION
**Pull request by louwers**
This is a continuation of #674 where @alanchengrab enabled C++ unit tests on macOS.

Instead of adding another entry to the Makefile I have changed things a bit so that the test can be built and ran through CMake & CTest (thanks @ntadej for the suggestion).

I removed the C++ wrapper around that forks and runs the Node.js server, and instead made a Node.js wrapper that forks to run the test. This approach is more platform indepentent, which will be helpful if we will use the Node.js based HTTP server for tests of other platforms in the future.

### CODE REVIEW

**Comment by ovivoda** [comment]
hmm @louwers This looks odd:

Screenshot 2023-02-02 at 21 24 51

**Comment by louwers** [comment]
@ovivoda Yup, I'll have a look.

**Comment by alanchenboy** [comment]
Thanks for pick this up.

My origin pr runs the server at the root dir because the CPP unit test is not a macOS CPP unit test, just the mbgl-test project of macOS version. So if it's not running at the root dir the resources in the test directory will not be loaded successfully. and that's why the unit test can't pass.

BTW some objects in the macOS targets can't work, the node objects, the `test-render-runner`. 

this unit test is quite like the `Run render tests on *`,  in node-ci.

**Comment by louwers** [comment]
@alanchenboy The root dir is still used as working directory, but I just made an out of source build.

As part of #737 I am investigating if we can move more stuff out of the custom Makefile and into CMake.

@ovivoda Turns out I forgot to push a file.

**Comment by ntadej** [comment]
Thanks for working on this! I'll look at it in detail tomorrow.

For reworking the scripts, we may want to wait for platforms reorganisation. I should have a draft of the proposal this weekend.

**Comment by louwers** [comment]
I'm not sure if the tests are being run:

image

**Comment by alanchenboy** [comment]
`mbgl-test-runner` cost 0.06 seconds I think this means no unit tests runed

**Pull request closed without merging**
