### PR TITLE
Make MapboxFusedLocationEngineImpl contrcutor public

### PR DESCRIPTION
**Pull request by jDilshodbek**
Making MapboxFusedLocationEngineImpl constructor public to access in custom LocationEngineProvider class

### CODE REVIEW

**Review by louwers — CHANGES_REQUESTED** [review]
You seem to have comitted your `.gradle` directory.

**Comment by jDilshodbek** [comment]
Oops, they are following my new commits as well, how can I omit them?

**Comment by louwers** [comment]
@jDilshodbek I can make a PR as well if you want.

**Comment by jDilshodbek** [comment]
I reforked. I will make new pull request from new fork

**Pull request closed without merging**
