### PR TITLE
Update CI runners to macos 11

### PR DESCRIPTION
**Pull request by birkskyum**
macos-10.15 is not deprecated in github actions, and macos-11 is the smallest step we can take here.

### CODE REVIEW

**Comment by ntadej** [comment]
There was no really need to fix the `latest` versions, but it's fine in any case.

**Comment by roblabs** [comment]
The `iOS-ci` build is failing due to a single test related to snapshotter:  `-[MGLOfflineStorageTests testAddPackForBounds]`

---

PR https://github.com/maplibre/maplibre-gl-native/pull/411 addresses this failure and upgrades the GitHub Workflow to `runs-on: macos-12`.

**Comment by roblabs** [comment]
Looks our iOS & macOS Workflows are blocked.  @ntadej  or @birkskyum.

> This is a scheduled macOS-10.15 brownout. The macOS-10.15 environment is deprecated and will be removed on August 30th, 2022. For more details, see https://github.com/actions/virtual-environments/issues/5583

> GitHub Actions has encountered an internal error when running your job.

> [ios-ci: .github#L1](https://github.com/maplibre/maplibre-gl-native/pull/419/files#annotation_4497003139)
The macOS-10.15 environment is deprecated, consider switching to macos-11(macos-latest), macos-12 instead. For more details see https://github.com/actions/virtual-environments/issues/5583

---

image

**Comment by birkskyum** [comment]
We got this error on both mac 12 and ios 15.5, so I added a small patch that does this invalidation.

Screen Shot 2022-09-03 at 19 28 57

**Pull request closed without merging**
