### PR TITLE
[iOS]Fix image comparison failed on Xcode 14.1

### LINKED ISSUE #573: CI is failing for iOS
The workflow `ios-ci.yml` is failing. I don't know why but the console says something like this:

```
MGLCodingTests
  testAnnotationImage, ((annotationImage) equal to (unarchivedAnnotationImage)) failed: ("<MGLAnnotationImage: 0x6000025110e0>") is not equal to ("<MGLAnnotationImage: 0x600002510ba0>")
  /Users/ec2-user/actions-runner/_work/maplibre-gl-native/maplibre-gl-native/platform/ios/platform/darwin/test/MGLCodingTests.mm:552
```

### PR DESCRIPTION
**Pull request by alanchenboy**
Image data comparison failed even though the data is the same on Xcode 14.1.

Fixes #573

### CODE REVIEW

**Comment by wipfli** [comment]
Cool, thanks @alanchenboy for the fix and @mwilsnd for the review. I'm excited to see our ios-ci green again!

**Review by wipfli — APPROVED** [review]

**Comment by roblabs** [comment]
I restarted the `ios-ci` build due to this weird issue file I/O issue:

https://github.com/maplibre/maplibre-gl-native/actions/runs/3696507920/jobs/6260295754#step:14:3099

`NSFileHandle couldn't write. Error: Error Domain=NSCocoaErrorDomain Code=512 "The file couldn’t be saved." UserInfo={NSUnderlyingError=0x6000009d9140 {Error Domain=NSPOSIXErrorDomain Code=32 "Broken pipe"}}`


```
Test Suite iosapp UITests.xctest started
[3087](https://github.com/maplibre/maplibre-gl-native/actions/runs/3696507920/jobs/6260295754#step:14:3088)
iosapp_UITests
[3088](https://github.com/maplibre/maplibre-gl-native/actions/runs/3696507920/jobs/6260295754#step:14:3089)
/Library/Ruby/Gems/2.6.0/gems/xcpretty-0.3.0/lib/xcpretty/parser.rb:434:in `===': invalid byte sequence in US-ASCII (ArgumentError)
[3089](https://github.com/maplibre/maplibre-gl-native/actions/runs/3696507920/jobs/6260295754#step:14:3090)
	from /Library/Ruby/Gems/2.6.0/gems/xcpretty-0.3.0/lib/xcpretty/parser.rb:434:in `update_test_state'
[3090](https://github.com/maplibre/maplibre-gl-native/actions/runs/3696507920/jobs/6260295754#step:14:3091)
	from /Library/Ruby/Gems/2.6.0/gems/xcpretty-0.3.0/lib/xcpretty/parser.rb:307:in `parse'
[3091](https://github.com/maplibre/maplibre-gl-native/actions/runs/3696507920/jobs/6260295754#step:14:3092)
	from /Library/Ruby/Gems/2.6.0/gems/xcpretty-0.3.0/lib/xcpretty/formatters/formatter.rb:88:in `pretty_format'
[3092](https://github.com/maplibre/maplibre-gl-native/actions/runs/3696507920/jobs/6260295754#step:14:3093)
	from /Library/Ruby/Gems/2.6.0/gems/xcpretty-0.3.0/lib/xcpretty/printer.rb:19:in `pretty_print'
[3093](https://github.com/maplibre/maplibre-gl-native/actions/runs/3696507920/jobs/6260295754#step:14:3094)
	from /Library/Ruby/Gems/2.6.0/gems/xcpretty-0.3.0/bin/xcpretty:84:in `block in <top (required)>'
[3094](https://github.com/maplibre/maplibre-gl-native/actions/runs/3696507920/jobs/6260295754#step:14:3095)
	from /Library/Ruby/Gems/2.6.0/gems/xcpretty-0.3.0/bin/xcpretty:83:in `each_line'
[3095](https://github.com/maplibre/maplibre-gl-native/actions/runs/3696507920/jobs/6260295754#step:14:3096)
	from /Library/Ruby/Gems/2.6.0/gems/xcpretty-0.3.0/bin/xcpretty:83:in `<top (required)>'
[3096](https://github.com/maplibre/maplibre-gl-native/actions/runs/3696507920/jobs/6260295754#step:14:3097)
	from /usr/local/bin/xcpretty:23:in `load'
[3097](https://github.com/maplibre/maplibre-gl-native/actions/runs/3696507920/jobs/6260295754#step:14:3098)
	from /usr/local/bin/xcpretty:23:in `<main>'
[3098](https://github.com/maplibre/maplibre-gl-native/actions/runs/3696507920/jobs/6260295754#step:14:3099)
2022-12-14 16:05:39.076 xcodebuild[82042:37411378] NSFileHandle couldn't write. Error: Error Domain=NSCocoaErrorDomain Code=512 "The file couldn’t be saved." UserInfo={NSUnderlyingError=0x6000017a0180 {Error Domain=NSPOSIXErrorDomain Code=32 "Broken pipe"}}
[3099](https://github.com/maplibre/maplibre-gl-native/actions/runs/3696507920/jobs/6260295754#step:14:3100)
2022-12-14 16:05:39.105 xcodebuild[82042:37411378] NSFileHandle couldn't write. Error: Error Domain=NSCocoaErrorDomain Code=512 "The file couldn’t be saved." UserInfo={NSUnderlyingError=0x6000009e7600 {Error Domain=NSPOSIXErrorDomain Code=32 "Broken pipe"}}

```

**Comment by roblabs** [comment]
I'm not sure it's worth root causing, but I did restart the build from `main` to ensure we go green.  And indeed this [action](https://github.com/maplibre/maplibre-gl-native/actions/runs/3696507920) is now showing green.

**Comment by roblabs** [comment]
Thank for contributing to FOSS4G, @alanchenboy!!

**Comment by alanchenboy** [comment]
Hi @roblabs, The failing CI is caused by the main branch, and I already fix it https://github.com/maplibre/maplibre-gl-native/pull/599. 
After rebasing all Unit tests passed.

**Pull request merged**
