### PR TITLE
Remove GLKView.snapshot to prevent the app from crash

### LINKED ISSUE #566: Crash Caused by GLKView.snapshot (Grab has bugfix)
## Summary

Delete snapshot when app switches to the background.
## Grab has bugfix
The original author of this bug report is Grab. They have a bug fix and would like to upstream it to MapLibre GL Native.

### PR DESCRIPTION
**Pull request by alanchenboy**
GLKView.snapshot can crash the app randomly, GrabMap just removes it to prevent the app from crashing.

Fixes #566

### CODE REVIEW

**Comment by birkskyum** [comment]
Is it unlikely that this code is used by someone?

**Comment by alanchenboy** [comment]
> Is it unlikely that this code is used by someone?

I think it not execute in SDK. The purpose for these code is: before enter background, the sdk take a snapshot then use a image view cover the whole map, and pause the map rendering to save energy. But GLKView.snapshot just randomly crash, so I think mapbox turn it off by config, and from user view this function is not acceptable, the snapshot is not same with the map when the map bring to front user can get a jump for map because the snapshot view is not as same as the gl view.

**Comment by ovivoda** [comment]
I started by asking a question in maplibre-ios slack channel to double check if anyone is actually using this snapshot feature. 
I suggest we wait a bit, maybe we should define this wait times btw to 1 week or 10 days, before merging this PR's. Just in case someone is using that code part already.

**Comment by ovivoda** [comment]
@alanchenboy can you please help out by resolving the conflicts. Tx!

**Comment by alanchenboy** [comment]
Rebased

**Comment by ovivoda** [comment]
It has been two weeks since I asked this on slack. No response back so I think we are safe to merge it. @birkskyum please advice otherwise.

**Comment by birkskyum** [comment]
I agree with merging

**Review by birkskyum — APPROVED** [review]

**Pull request merged**
