### PR TITLE
Fix compass warning in the MGLMapView

### PR DESCRIPTION
**Pull request by nvanfleet**
I was getting this error but I had set the compass visibility to hidden (But not the UIView setting of isHidden).

I think the logic for this error should check one, or both, of the isHidden values.

### CODE REVIEW

**Comment by birkskyum** [comment]
@nvanfleet , if you rebase this branch to main, the CI should run properly.

**Comment by nvanfleet** [comment]
> @nvanfleet , if you rebase this branch to main, the CI should run properly.

@birkskyum done

**Review by ntadej — APPROVED** [review]

**Comment by ntadej** [comment]
Looks good for me. I wonder if we should add a changelog entry for iOS.

**Comment by nvanfleet** [comment]
> Looks good for me. I wonder if we should add a changelog entry for iOS.

@ntadej done

**Pull request merged**
