### PR TITLE
Enable Address Sanitizer, etc., in CI

### PR DESCRIPTION
**Pull request by TimSylvester**
Also testing cross-fork PRs, and running CI in the MGN repo before bothering anyone with reviews.

#947

### CODE REVIEW

**Review by louwers — APPROVED** [review]

**Comment by louwers** [comment]
@TimSylvester Would you mind adding these files as a dependency to the relevant GitHub Actions workflow? (ios-ci)

**Comment by TimSylvester** [comment]
@louwers I'm not familiar with Actions, but I can give it a shot.  Which files, though, the `.xcscheme`?

**Comment by louwers** [comment]
A glob pattern here

https://github.com/maplibre/maplibre-gl-native/blob/main/.github/workflows/ios-ci.yml#L10

And here:

https://github.com/maplibre/maplibre-gl-native/blob/main/.github/workflows/ios-ci.yml#L30

Docs:

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore

You can use a wildcard.

**Comment by TimSylvester** [comment]
`platform/ios/platform/ios/ios.xcodeproj` will be included by `platform/ios/**` though, and the actions did run when I created the PR.

**Comment by louwers** [comment]
My bad, they already ran.

**Pull request merged**
