### PR TITLE
Update wagyu to v0.5.0

### PR DESCRIPTION
**Pull request by birkskyum**

### CODE REVIEW

**Review by roblabs — CHANGES_REQUESTED** [review]
The check for the iOS workflow failed for when `wagyu` changed.  I've submitted a re-run of the workflow to see it were an anomaly.  We'll need to monitor and see if it passed.

**Comment by birkskyum** [comment]
@roblabs , so it was an anomaly?

**Comment by ntadej** [comment]
It seems so. Unfortunately I'm sick at the moment so I'll leave it up to him to merge. Sorry for the delay.

**Comment by roblabs** [comment]
> *@roblabs , so it was an anomaly?*

Let's track my change requests over on: https://github.com/maplibre/maplibre-gl-native/pull/205#issuecomment-1028421436

**Pull request closed without merging**
