### PR TITLE
Fix typo in geo.cpp

### PR DESCRIPTION
**Pull request by ntadej**
Fix (old!) typo in `geo.cpp` to allow building for Android using new SDKs.

### CODE REVIEW

**Review by wipfli — APPROVED** [review]
How old is it?

**Comment by wipfli** [comment]
Ah, can you add a changelog item?

**Comment by ntadej** [comment]
5 years or so.

Also do such items really require a changelog item?

**Comment by wipfli** [comment]
I don't know, up to you... We might want to have some automated changlog generation in the future.

**Comment by ntadej** [comment]
Merging for now then 😊

**Comment by wipfli** [comment]
Great thanks, should we update at some point the Android SDK version used in CI?

**Comment by ntadej** [comment]
I'd wait a bit with that until we have better understanding how it works.

I updated the description now, it was actually NDK that was newer (SDK is for java stuff, NDK is for native compilation).

**Comment by roblabs** [comment]
iOS builds did not error/warning when it was either `&` or `&&`.

**Comment by ntadej** [comment]
> iOS builds did not error/warning when it was either `&` or `&&`.

Yes, I assume newer NDKs have stricter warnings/checks enabled.

**Pull request merged**
