### PR TITLE
Add design proposal guidelines

### PR DESCRIPTION
**Pull request by wipfli**
I think it is useful to first think and discuss larger changes to MapLibre GL Native before starting to implement them. This pull request introduces some guidelines who people can make a Design Proposal.

The structure is inspired by Apache Kafka, https://cwiki.apache.org/confluence/display/kafka/kafka+improvement+proposals. Thanks @hy9be for providing this reference!

### CODE REVIEW

**Review by birkskyum — APPROVED** [review]

**Comment by birkskyum** [comment]
@wipfli It's a great idea, but I can't make the CI pass for some reason.

**Comment by hy9be** [comment]
Thanks @wipfli !

**Comment by wipfli** [comment]
The CI output says something about macos not being supported:

> This is a scheduled macOS-10.15 brownout. The macOS-10.15 environment is deprecated and will be removed on August 30th, 2022

**Comment by wipfli** [comment]
I guess we need a newer macOS version?

**Comment by wipfli** [comment]
And yes, sure, let's discuss the process on Sep 14th, 2022 in the next Technical Steering Committee meeting.

**Comment by ntadej** [comment]
Yes, but this is out of scope of this PR.

**Pull request merged**
