### PR TITLE
iOS size test

### PR DESCRIPTION
**Pull request by alexcristici**
Building the app for 2 configurations: Release and MinSizeRel, and comparing the MapLibre dynamic library size with saved sizes before starting the modularization and migration to Metal.

### CODE REVIEW

**Comment by sjg-wdw** [comment]
Over the years Xcode has moved its build around, changed its arguments and such.
I wonder if you could put some checks around the xcode invocation and double check that the build directory exists.

**Review by TimSylvester — APPROVED** [review]
We're depending on the signing key being set up in the test runner, right?  I don't see anything about it here, which is good.

**Comment by alexcristici** [comment]
> We're depending on the signing key being set up in the test runner, right? I don't see anything about it here, which is good.

Yes, the command line for running the size test is: `make ios-sizetest DEV_TEAM=[TEAM_ID]`. Maybe we will change to use the prov and signing certificate directly if needed. We will see when we will reach the point to add it on GitHub CI.

**Review by mwilsnd — APPROVED** [review]

**Comment by sjg-wdw** [comment]
> Over the years Xcode has moved its build around, changed its arguments and such. I wonder if you could put some checks around the xcode invocation and double check that the build directory exists.

To provide a bit more context, I've had framework building scripts that have broken several times over the years and it's never clear why.  It would be nice to provide whomever deals with this in 3 years a starting point for which part of it is failing.

**Comment by sjg-wdw** [comment]
> > > Over the years Xcode has moved its build around, changed its arguments and such. I wonder if you could put some checks around the xcode invocation and double check that the build directory exists.
> > 
> > 
> > To provide a bit more context, I've had framework building scripts that have broken several times over the years and it's never clear why. It would be nice to provide whomever deals with this in 3 years a starting point for which part of it is failing.
> 
> Yes, I added checks after each step. Let me know if I missed something.

Looks great!

**Review by sjg-wdw — APPROVED** [review]

**Review by louwers — APPROVED** [review]
I can’t try this out yet but LGTM.

Feel free to merge.

**Pull request merged**
