### PR TITLE
first commit

### PR DESCRIPTION
**Pull request by tarunsamanta2k20**
#907 
ask me once for changes if any.

### CODE REVIEW

**Comment by louwers** [comment]
@tarunsamanta2k20 Hi thanks for contributing to MapLibre GL Native.

That preprocessor macro is used in that same file, so to remove it you have to rewrite that a bit.

**Comment by louwers** [comment]
@tarunsamanta2k20 It seems to be some kind of version check. Why do you think it can be removed completely?

**Comment by louwers** [comment]
Also please give your pull requests a descriptive title.

**Comment by tarunsamanta2k20** [comment]
@

> @tarunsamanta2k20 It seems to be some kind of version check. Why do you think it can be removed completely?

Please suggest me what I have to do?

**Comment by louwers** [comment]
> @
> 
> > @tarunsamanta2k20 It seems to be some kind of version check. Why do you think it can be removed completely?
> 
> Please suggest me what I have to do?

Do you know C++ and the C preprocessor?

**Comment by tarunsamanta2k20** [comment]
> > @
> > > @tarunsamanta2k20 It seems to be some kind of version check. Why do you think it can be removed completely?
> > 
> > 
> > Please suggest me what I have to do?
> 
> Do you know C++ and how preprocessor macros work?

@louwers yes

**Comment by louwers** [comment]
You should be able to run this file through the preprocessor to be able to replace the macro.

**Pull request closed without merging**
