### PR TITLE
Run node-ci on changes to macOS, Linux & Windows platforms

### PR DESCRIPTION
**Pull request by louwers**

### CODE REVIEW

**Review by ovivoda — APPROVED** [review]
Looks legit!

**Comment by acalcutt** [comment]
If you are going to add windows, doesn't it make sense to include macos and linux too?

**Comment by louwers** [comment]
> If you are going to add windows, doesn't it make sense to include macos and linux too?

I'm not sure, are there files of the macOS or linux platforms that do not get compiled on CI?

**Comment by acalcutt** [comment]
I don't think it makes sense to run it on all iOS/Android/QT changes. that ci still has that annoying xfrb crash. If you look at the cmakelists file, linux/macos/windows only get run in a core build or node build.

**Pull request merged**
