### PR TITLE
Organize source code based on tree folders

### PR DESCRIPTION
**Pull request by alexcristici**
I organized only the core files and iOS files.
For organizing the other platform specific files, just follow the same logic as in `ios.cmake`.

### CODE REVIEW

**Comment by sjg-wdw** [comment]
I'm excited for this one, but I'm curious how the maintainers feel.

**Review by sjg-wdw — APPROVED** [review]

**Review by TimSylvester — APPROVED** [review]
So much nicer, thank you!

**Review by ntadej — APPROVED** [review]
No objections for me if it helps how Xcode project is structured. I suspect not many other platforms are affected by external project organisation so it's fine to only do it for iOS at this point.

**Review by mwilsnd — APPROVED** [review]
This also works when generating a Visual Studio solution. We can change the Windows CMake later though, no rush!

**Pull request merged**
