### PR TITLE
Fix platform linux

### PR DESCRIPTION
**Pull request by xabbu42**
This are the necessary changes to fix the build on linux after commit d62ff400c6f75750d71b563344b1ca1e07b9b576

I used maptiler config for mbgl-render and mbgl-glfw as this config was already used for mbgl-offline.

### CODE REVIEW

**Comment by xabbu42** [comment]
I seem to have copy pasted the wrong commit sha at first in my previous message. This is now fixed to the correct sha d62ff400c6f75750d71b563344b1ca1e07b9b576.

**Comment by petr-pokorny-1** [comment]
Cherry picking #144 into this PR should fix android-ci-pull, correct?

**Review by petr-pokorny-1 — APPROVED** [review]
Looks good, thanks!

**Comment by xabbu42** [comment]
No idea why macos-ci failed here. All checks succeeded in #135 which includes this commits as well, so I think thats a fluke. Perhaps its easiest to just merge #135 and close this one?

**Comment by petr-pokorny-1** [comment]
> No idea why macos-ci failed here. All checks succeeded in #135 which includes this commits as well, so I think thats a fluke. Perhaps its easiest to just merge #135 and close this one?

Looks like the 2nd attempt passed.

**Pull request merged**
