### PR TITLE
Use MetalANGLE wrapper classes.

### PR DESCRIPTION
**Pull request by sulewicz**
Hello!

Here is the initial PR for a preview version of MapLibre with Metal support. Kudos to kakashidinho for his hard work on https://github.com/kakashidinho/metalangle!

Here are the instructions to build the test "iosapp" target:
1. `cd <MapLibre>/`
1. `git submodule update --init --recursive`
1. `cd <MapLibre>/platform/ios/platform/ios/vendor/metalangle/ios/xcode`
1. `./fetchDependencies.sh`
1. `cd <MapLibre>/platform/ios`
1. `make iproj`
1. In XCode build and run "iosapp" target.

Known problems:
1. I have tested the Metal version only in the Simulator so far.
1. I haven't tried the "static" build yet.
1. Building "bench" requires switching the "Run" schema to "Debug".
1. No proper CI integration yet.

Things to consider:
1. Should we move the MetalANGLE library to a different folder, e.g., if we want to support OSX?
1. Should we support two flavors (Metal and OpenGL), or should we migrate fully to Metal?

I hope we will address the known (and newly discovered) problems in the subsequent PRs.

### CODE REVIEW

**Review by roblabs — COMMENTED** [review]
In order to deploy to a device, I had to add a User-Defined variable Xcodeproj In the Submodule for [MetalANGLE](https://github.com/kakashidinho/metalangle)

* Target > MetalANGLE > Build Settings > Basic & Levels 
  * `BITCODE_GENERATION_MODE` is set to `bitcode`


image

**Review by petr-pokorny-1 — APPROVED** [review]
Looking good! I am going to merge it into metal-support branch so that we can continue working on packaging scripts. I will implement Robs comments in separate PR

**Comment by roblabs** [comment]
Results after determining if a build can be archived and validated by App Store Connect.

* App Store Connect Error after performing Xcode > `Product` > `Archive`.  Xcode Organizer > `Validate App`.
* Note there is no error referencing `MetalANGLE` as in this https://github.com/maplibre/maplibre-gl-native/pull/40#discussion_r588698187 from above.
- [ ] The proper test would also include archiving a build from Swift PM.  This test is from building `iosapp` from scratch.
---

> App Store Connect Operation Error
Invalid Bundle. The bundle at 'MapLibre GL.app/Frameworks/Mapbox.framework' contains disallowed nested bundles.

> App Store Connect Operation Error
Invalid Bundle. The bundle at 'MapLibre GL.app/Frameworks/Mapbox.framework' contains disallowed file 'Frameworks'.

image

**Comment by roblabs** [comment]
Update on the Archiving & App Store Connect reported [here.](https://github.com/maplibre/maplibre-gl-native/pull/40#issuecomment-805919029).

* @petr-pokorny-1's PR #50 fixed the issues around nested frameworks.  Please see that PR for further testing results on his work.

**Pull request merged**
