### PR TITLE
chore: rename master -> main in CI and build scripts

### PR DESCRIPTION
**Pull request by atierian**
Issue:
https://github.com/maplibre/maplibre/issues/11

Changes:
This PR makes a best effort to change all CI and related build scripts from using `master` to `main`.

Explicitly excluded from changes:
- `**/vendor`
- Any  `**/mapbox/**` links. While the majority of these could be renamed already, it would make more sense to handle these changes while updating the links to point at `maplibre`.
- Any occurrences of `master` in links to third party licenses.
- Any occurrences of `master` in functional code.

Once this is merged, we can take the remaining steps listed in the linked issue to complete the rename.

### CODE REVIEW

**Review by Milan-Shah — APPROVED** [review]

**Review by thaddmt — APPROVED** [review]

**Review by roblabs — APPROVED** [review]

**Comment by roblabs** [comment]
@atierian — Just realized:  The GitHub workflow won't kick off because the  touched files are in the *ignore list* for triggering a GitHub Workflow.  So we'll monitor this after the next PR.  

**OR**, do you recommend committing something (say in a SwiftUI test app) that will trigger *all the builds.*?

**Comment by ntadej** [comment]
I think the problem is rather that the trigger branches in the CI configs were switched to `main` already.

**Comment by atierian** [comment]
Another option would be:
1. Reverting the commit
2. Changing the branch name
3. Merging this reverted commit.

If the files are in the GitHub action / workflow ignore list, the tests can be manually triggered.

Since this PR touches so many files, I'd like to make sure CI is working as expected before any code changes get merged to main.

**Comment by roblabs** [comment]
Let's try the manual trigger method.  Under the [checks](https://github.com/maplibre/maplibre-gl-native/pull/246/checks?sha=a306553d8ebb1f6903a0a46eacea698dfce71d9b) section of a PR, I usually see a way to rebuild, but I don't see that for this one.

If there is another way to trigger, please let me know.

**Comment by ntadej** [comment]
Directly from Actions (one by one). I did that for all `*-ci` ones now.

**Comment by roblabs** [comment]
Thanks @ntadej  — I see it now, and thanks for kicking off those actions

* https://github.com/maplibre/maplibre-gl-native/actions

**Pull request merged**
