### PR TITLE
Remove firebase step from android-release workflow

### PR DESCRIPTION
**Pull request by wipfli**
The firebase step currently fails and blocks us from making an android release. I think we should just release what we have now, and then figure out why the test fails and fix it for future releases...

### CODE REVIEW

**Review by boldtrn — APPROVED** [review]
Makes sense, we can always add this again when it's fixed.

**Comment by wipfli** [comment]
Added a note about the firebase testing at https://github.com/maplibre/maplibre-gl-native/issues/605#issuecomment-1357608817

**Comment by wipfli** [comment]
I will move the `android-v9.6.0` tag to the latest commit, because the release workflow checks out the repo at the latest tag starting with android.

According to 
https://stackoverflow.com/questions/8044583/how-can-i-move-a-tag-on-a-git-branch-to-a-different-commit

I can do 

Delete the tag on any remote before you push

```
git push --atomic origin main android-v9.6.0
```

Replace the tag to reference the most recent commit

```
git tag -fa android-v9.6.0
```

Push the tag to the remote origin

```
git push origin main --tags
```

**Comment by wipfli** [comment]
I can delete the android-v9.6.0 tag with 
image

at https://github.com/maplibre/maplibre-gl-native/tags

**Comment by wipfli** [comment]
Deleted the android-v9.6.0 tag via web interface

**Pull request merged**
