### PR TITLE
[qt] Add a test for library usage

### PR DESCRIPTION
**Pull request by ntadej**
As discussed at the last technical steering meeting, I'm adding a simple test to run on the tarball contents to test if it configures and compiles.

### CODE REVIEW

**Comment by ntadej** [comment]
This one is ready. Node failures are unrelated.

**Review by wipfli — APPROVED** [review]
Thanks Tadej

**Comment by wipfli** [comment]
Can you make a follow up pull request with a bug or so such that we can check that it actually detects build problems?

**Comment by ntadej** [comment]
Actually this already fixes a bug or improves the deployment as tarball created on CentOS did not directly work on Ubuntu (due to different library folder). But yes, I can try to break it again. Will you click the merge button?

**Pull request merged**
