### PR TITLE
Dependecy upgrades

### PR DESCRIPTION
**Pull request by birkskyum**
Instead of many small PR's with version updates, this will update most of our dependencies, so if we can test this branch and make it work we are a big step in the right direction. @roblabs  @ntadej 

The CI/CD environments are generally a bit outdated, so let's update those first ( see #387 ).

### CODE REVIEW

**Comment by ntadej** [comment]
Do not update maplibre-gl-js in this one. It will not work due to shaders.

**Comment by birkskyum** [comment]
Okay, I have reverted the change to submodule.

**Comment by birkskyum** [comment]
I reverted the bump of benchmark from 1.5 to 1.7, because google apparently against semver introduced breaking changed in the 1.6 minor release.

**Comment by ntadej** [comment]
The CI OS versions commit may be more suitable for a separate PR, but it's probably fine here :)

**Comment by birkskyum** [comment]
> The CI OS versions commit may be more suitable for a separate PR, but it's probably fine here :)

I think you are very right about that. There is a PR in here #388

**Comment by birkskyum** [comment]
closed in favour of smaller increments.

**Pull request closed without merging**
