### PR TITLE
cleaner includes in 'util'

### PR DESCRIPTION
**Pull request by bencsikandrei**
Hello, 

First time contribution to the project, getting to know it and while browsing through the bits and pieces (with some helpful-ish input from IWYU) I've found a couple places where headers were either forgotten or not useful.

I'd like to go through some more of the project and if this PR is welcome I'll probably go ahead and do more.

I've read through the useful rampup files (like DEVELOPING.md, etc...) but if there's something I'm missing please let me know so that I can improve this or the PRs to come.

Thanks!

### CODE REVIEW

**Comment by louwers** [comment]
@bencsikandrei Thanks. Clean up is welcome, but it seems the build fails.

**Comment by bencsikandrei** [comment]
hope I caught them all

I've been doing this without access to a macos machine and I hate relying on the CI for these... if it still fails I'll try to use a docker to get as close as possible to an apple-clang and an older version of libstdc++ and gcc

fingers crossed :crossed_fingers:

**Comment by louwers** [comment]
Thanks @bencsikandrei, you are a MapLibre Native contributor now!

**Comment by bencsikandrei** [comment]
Thank you!

I was wondering what the failure was on one of the jobs:
```
# double release
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open X display.
Aborted (core dumped)
```
is it acceptable in this case?

**Pull request merged**
