### PR TITLE
Better MinGW build support

### PR DESCRIPTION
**Pull request by tdcosta100**
If you ever tried to build the entire project with MinGW (specially Qt and the test targets) instead only the core projects or using Microsoft Visual Studio, you will discover it's painful. This PR allows to build with MinGW a smoother process.

### CODE REVIEW

**Comment by ntadej** [comment]
Thanks for looking into this!

As I mentioned in the discussion, I'm not sure how many people actually use MinGW. In my experience MSVC always built faster and gave smaller binary sizes (plus it's easier to use the Windows APIs).

**Comment by tdcosta100** [comment]
Yeah, I use MSVC too, it's so much better. But since there is MinGW in CI, so it's fair to provide it better support, I guess. Some tests failed because it was a connection error while checking out the repository. Could you please re-run the failed workflows?

**Comment by ntadej** [comment]
If we ever want to be included back in the Qt distribution, we need to support it at least for latest Qt 6.

**Comment by tdcosta100** [comment]
I agree with you, if MinGW support is dropped, I won't complain.

**Comment by tdcosta100** [comment]
node-ci is failing with Mac OS 12, but I think with #926 merged, it won't fail anymore.

**Review by louwers — APPROVED** [review]

**Pull request merged**
