### PR TITLE
Bump earcut.hpp to v2.2.4

### PR DESCRIPTION
**Pull request by SiarheiFedartsou**
It contains a couple of bug fixes like this https://github.com/mapbox/earcut.hpp/commit/4811a2b69b91f6127a75e780de6e2113609ddabb

### CODE REVIEW

**Comment by ntadej** [comment]
Which version do we have now?

**Comment by SiarheiFedartsou** [comment]
> Which version do we have now?

I think it has no tag, but it points to this commit https://github.com/mapbox/earcut.hpp/tree/0d0897a9dc462edf6396aedb335ddeb4aa302b78

**Comment by SiarheiFedartsou** [comment]
@ntadej do you think some CI jobs are broken due to this update? Or it was already broken before?

**Comment by ntadej** [comment]
It seems network issues, let me retry.

**Comment by SiarheiFedartsou** [comment]
@ntadej it seems now it is okay

**Review by louwers — APPROVED** [review]

**Review by louwers — APPROVED** [review]
Related #990

**Pull request merged**
