### PR TITLE
Use self-hosted AWS runners

### PR DESCRIPTION
**Pull request by birkskyum**
Run macos-ci and ios-ci on dedicated M1 AWS instance, to cut down on CI times.

macos-ci: 20 min -> 2 min.
ios-ci: 108 min -> 22 min.

### CODE REVIEW

**Comment by birkskyum** [comment]
@roblabs, @nvanfleet , if anyone of you are familiar with the arch compiler options in xcode, we have a possibility here to dramatically cut ci times for ios/macos builds. There is a arch (x86_64 and arm64) mismatch in our ios-ci that I'm not sure how to resolve. I believe this CI is expecting an arm64 build, where our previous one expected x86_64 builds, but our ios->test target, apparently generates x86_64 builds.

**Comment by birkskyum** [comment]
In the ios-ci runner. https://github.com/maplibre/maplibre-gl-native/runs/8228993960?check_suite_focus=true

Screen Shot 2022-09-07 at 16 06 33

**Comment by birkskyum** [comment]
It's this  part: `(mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))` that seems to make trouble. I've found that if I tick "Enable Bitcode" in the Build Settings of ios->test, it seems like that these libmbgl core dependencies used by ios->test  (on the picture) maybe aren't arm64 compiled at this point.
image

**Comment by nvanfleet** [comment]
> @nvanfleet do you think the bazel build scripts can solve this?

Oh this is really interesting. I haven't covered the test targets for the bazel scripts so far, but it seems feasible that we could select arch for running those in the bazel script. I can look into this.

**Comment by birkskyum** [comment]
@nvanfleet thanks! It would be really helpful.

**Comment by birkskyum** [comment]
It's finally working as expected.

**Comment by wipfli** [comment]
Thanks for fixing the CI on main and getting the self-hosted M1 runners up, Birk. Looks good to me. I guess you merged because main was broken?

**Comment by wipfli** [comment]
Should we open an issue to remember the two disabled tests `"MGLOfflineStorageTests", "MGLMapViewContentInsetTests"`?

**Comment by birkskyum** [comment]
@wipfli , good idea - I made an issue ( #432 ). I actually patched and enabled the MGLOfflineStorageTests just yesterday (#428), but apparently, these CI checks find that there is still something missing which is why I turned it off again.

**Comment by roblabs** [comment]
I would like to request that we re-enable the test from the `iosapp` scheme called `testDebugBoundaryTiles()`

This will help us diagnose #268 (which currently fails on iOS 15 simulators; works on iOS 16 simulators)

* Turns on the red tile boundary
* adds a green polyline at (0,0)
* Measure Frames per second (FPS decoration in the upper left)
* Takes a screen shot and saves it off.

image

**Pull request merged**
