### PR TITLE
Fix style code generation, remove package.json ios

### PR DESCRIPTION
**Pull request by louwers**

### CODE REVIEW

**Comment by roblabs** [comment]
I was able to get this to work, manually on my dev machine.  One thing I had to do to get this to work was run `npm i` from the repo's root folder.  I don't recall having to do that before for building the iOS SDK.

### Lots of changes files that need to be reviewed via `git status`

- [ ] Should these be checked in now to avoid this issue for developers?
- [ ] Should we add the _untracked_ file to the ignore list?

<details markdown=1 open><summary> results of <code>git status</code> </summary>
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   ../../include/mbgl/style/layers/background_layer.hpp
        modified:   ../../include/mbgl/style/layers/circle_layer.hpp
        modified:   ../../include/mbgl/style/layers/fill_extrusion_layer.hpp
        modified:   ../../include/mbgl/style/layers/fill_layer.hpp
        modified:   ../../include/mbgl/style/layers/heatmap_layer.hpp
        modified:   ../../include/mbgl/style/layers/hillshade_layer.hpp
        modified:   ../../include/mbgl/style/layers/line_layer.hpp
        modified:   ../../include/mbgl/style/layers/location_indicator_layer.hpp
        modified:   ../../include/mbgl/style/layers/raster_layer.hpp
        modified:   ../../include/mbgl/style/layers/symbol_layer.hpp
        modified:   ../../src/mbgl/style/layers/location_indicator_layer.cpp
        modified:   ../../src/mbgl/style/layers/location_indicator_layer_properties.hpp
        modified:   ../../src/mbgl/style/layers/symbol_layer_properties.hpp

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        ../../scripts/generate-style-code.list

</details>

---

### Build Dependencies Output
<details markdown=1><summary> Xcode 14.2 output </summary>

$ node ../../scripts/generate-shaders.js
make iproj. Opening MapLibre in Xcode using:  'xed platform/ios/ios.xcworkspace'.  To skip opening Xcode, use 'make iproj CI=1'
## Xcode dependencies
Xcode 14.2
Build version 14C18
Darwin oldSanJuan.local 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:42:11 PST 2023; root:xnu-8792.81.3~2/RELEASE_X86_64 x86_64
ProductName:            macOS
ProductVersion:         13.2.1
BuildVersion:           22D68
i386
ccache 4.7.4
cmake 3.25.2
glfw 3.3.8
pkg-config 0.29.2_3

</details>

**Comment by louwers** [comment]
@roblabs Thanks for trying it out.

I reverted the manually edited genrated files. I want to get rid of more checked in generated files later.

I ripped off the band-aid and got rid of the mostly duplicated `platform/ios/package.json`, let's see what problems occur.

**Comment by louwers** [comment]
Closed  #657

**Review by roblabs — APPROVED** [review]
Based on CI passing, a review via GitHub.com and running the original Makefile changes... I approve.

**Pull request merged**
