### PR TITLE
Add rust book for documenation

### PR DESCRIPTION
**Pull request by wipfli**
The goal of this pull request is to have a documentation website which is based on markdown files. I have copied over some files from maplibre-rs @maxammann thanks for the inspiration.

Probably the config is horribly wrong here, but it can serve as a starting point. @thehoneymad do you know what this justfile thing is?

Here is a demo on my fork: https://wipfli.github.io/maplibre-gl-native/docs/book/

### CODE REVIEW

**Comment by thehoneymad** [comment]
Putting an acknowledgement out here.

**Comment by thehoneymad** [comment]
@wipfli I think we should get this merged and get us started. :)

**Comment by wipfli** [comment]
Sounds good to me. Can you approve, @thehoneymad?

**Review by thehoneymad — APPROVED** [review]

**Comment by thehoneymad** [comment]
Marked as ready for review and approved the changes.

**Comment by maxammann** [comment]
I have been working on an RFC process for maplibre-rs which might be interesting for other projects aswell: https://github.com/maplibre/maplibre-rs/pull/188

**Comment by wipfli** [comment]
https://maplibre.org/maplibre-gl-native/docs/book/

**Pull request merged**
