### PR TITLE
Clean-up changelog

### PR DESCRIPTION
**Pull request by wipfli**
The changelog still uses `master`. This pull request replaces `master` with `main` and adds the sections again.

### CODE REVIEW

**Review by ntadej — APPROVED** [review]

**Comment by wipfli** [comment]
Or maybe the intention was that we use the changelogs in the platform folders. For example, here is a pull request that changed something in the core I think and the iOS and Android changelogs were updated:

https://github.com/maplibre/maplibre-gl-native/pull/34/files

**Comment by ntadej** [comment]
I think we need to separate "core" changelog and platform changelogs.

Maybe something to discuss at the next steering meeting.

**Comment by wipfli** [comment]
I added an agenda item.

**Comment by wipfli** [comment]
If the core and platform bindings were versioned independently and lived in separate projects, we would not get into this situation where one fix leads to two changelog updates...

**Pull request merged**
