### PR TITLE
Improve fling animation

### PR DESCRIPTION
**Pull request by Helium314**
PR for #927

This improves the fling animation with the main goal of the animation being similar to other maps.
See https://github.com/maplibre/maplibre-gl-native/issues/927#issuecomment-1486700986 for the reasons.
Short:
* UnitBezier parameters are adjusted for a less sudden stop of the fling animation
* Offset is now velocity / animationTime (with some mysterious factor, chosen so that animation starts at same velocity as the user moved the map)
* Animation base time and fling threshold can be set in UiSettings. In my opinion default threshold is too high, and animation time too short, making the map feel "sticky".

### CODE REVIEW

**Comment by louwers** [comment]
Neat! Could you update the android `CHANGELOG.md`?

**Comment by Helium314** [comment]
Sure!

Did you test it? I am not 100% sure the factor 0.28 will work on all screenDensities / tilts.
Especially with tilt testing is necessary (wasn't able to tilt, as mentioned in https://github.com/maplibre/maplibre-gl-native/issues/927#issuecomment-1486700986

What else is to be done?
* javadoc for changes in UI settings
* moving UI settings changes to "correct" position (not sure if there is any ordering / grouping of settings)
* maybe increasing `ANIMATION_DURATION_FLING_BASE` from `ANIMATION_DURATION_SHORT`to `ANIMATION_DURATION` (150 ms  is much too short in my opinion)

**Review by ovivoda — APPROVED** [review]
This looks good! Are you able to provide a video of the change in action on one of the native platforms?

**Comment by Helium314** [comment]
> This looks good! Are you able to provide a video of the change in action on one of the native platforms?

Same app on Android as in https://github.com/maplibre/maplibre-gl-native/issues/927#issuecomment-1480170974, but with the updated library with flingAnimationBaseTime set to 300 ms and flingThreshold set to 300:

https://user-images.githubusercontent.com/43007630/229335908-6a03dfa7-9c74-4126-990f-297d60070a7f.mp4

**Comment by ysmaherzi** [comment]
Hi,
This fix was published in the version 10.1.0 and is still present to this day on master but it's unavaiable on the latest stable 10.2.0.
Does someone know why ?

Thank you,

**Comment by louwers** [comment]
@ysmaherzi 10.2.0 reverted 10.1.0 because it contained a breaking change and should have been a major release.

Sorry for the confusion. This change will be included in the 11.0.0 release.

**Comment by ysmaherzi** [comment]
Thank you @louwers :)

**Pull request merged**
